apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ms12-cache-pdb
  namespace: zenia
  labels:
    app: ms12-cache
    component: disruption-budget
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: ms12-cache
