apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ms13-security-keycloak-monitor
  namespace: zenia
spec:
  selector:
    matchLabels:
      app: ms13-security-keycloak-exporter
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
