apiVersion: v1
kind: ConfigMap
metadata:
  name: ms13-security-config
  namespace: zenia
data:
  keycloak.conf: |
    # Configurazione Keycloak
    hostname: ms13-security-keycloak.zenia.svc.cluster.local
    db: postgres
    db-url: jdbc:postgresql://ms13-security-db:5432/keycloak
    db-username: keycloak
    db-password: ${KC_DB_PASSWORD}
    redis-host: ms13-security-redis
    redis-port: 6379
    redis-password: ${REDIS_PASSWORD}
    # Altre configurazioni custom
    # ...
