apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ms13-security-db
  namespace: zenia
  labels:
    app: ms13-security-db
spec:
  serviceName: ms13-security-db
  replicas: 1
  selector:
    matchLabels:
      app: ms13-security-db
  template:
    metadata:
      labels:
        app: ms13-security-db
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: keycloak
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: ms13-security-secrets
              key: db-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ms13-security-secrets
              key: db-password
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: ms13-security-db-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ms13-security-db-pvc
  namespace: zenia
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
