apiVersion: v1
kind: Service
metadata:
  name: ms13-security-keycloak
  namespace: zenia
spec:
  selector:
    app: ms13-security-keycloak
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: https
      port: 8443
      targetPort: 8443
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: ms13-security-db
  namespace: zenia
spec:
  selector:
    app: ms13-security-db
  ports:
    - name: db
      port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: ms13-security-redis
  namespace: zenia
spec:
  selector:
    app: ms13-security-redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: ms13-security-keycloak-exporter
  namespace: zenia
spec:
  selector:
    app: ms13-security-keycloak-exporter
  ports:
    - name: metrics
      port: 8081
      targetPort: 8081
  type: ClusterIP
