apiVersion: v1
kind: Service
metadata:
  name: ms14-audit-api
  namespace: zenia
spec:
  selector:
    app: ms14-audit-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: ms14-audit-es
  namespace: zenia
spec:
  selector:
    app: ms14-audit-es
  ports:
    - name: es-http
      port: 9200
      targetPort: 9200
    - name: es-transport
      port: 9300
      targetPort: 9300
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: ms14-audit-redis
  namespace: zenia
spec:
  selector:
    app: ms14-audit-redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: ms14-audit-exporter
  namespace: zenia
spec:
  selector:
    app: ms14-audit-exporter
  ports:
    - name: metrics
      port: 8081
      targetPort: 8081
  type: ClusterIP
